spring.application.name=bootcompany
spring.datasource.url=jdbc:mysql://localhost:3306/shopping_pu
spring.datasource.username=root
spring.datasource.password=Ayushi@2004

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=0
